### ISSUE TITLE
Do not use `cluster-admin` for LDAP group sync

### ISSUE THREAD

**Issue by corvus-ch** [appuio/component-openshift4-authentication#3]
The implementation in #1 uses the role `cluster-admin` to give permission for the LDAP group sync. This is probably too much power.

Find the minimal required permission and use them instead of role `clsuter-admin`.

**Comment by srueg** [comment]
The docs explicitly state to use the `cluster-admin` role:
> You must have cluster-admin privileges to sync groups.

https://docs.openshift.com/container-platform/4.4/authentication/ldap-syncing.html

Which kind of makes sense since adapting groups and users essentially grants cluster-admin anyways since one could add his user to a cluster-admin group anyways.
I'd propose to close this as "won't do".

**Comment by tobru** [comment]
I agree.
